[package]
name = "fanqie"
version = "1.0.0"
edition = "2026"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
vercel_runtime = "1"   # 核心运行时库

# 将每个 .rs 文件声明为一个独立的二进制程序
[[bin]]
name = "hello"
path = "api/hello.rs"